### ISSUE TITLE
Not Compatible with 60.3.0 :(

### ISSUE THREAD

**Issue by NJCurmudgeon** [conema/monterail-fulldark#24]
I'm sure you will be hearing from others, but the Monterail Full Dark theme is no longer compatible with Thunderbird 60.3.0. Also, when I tried the trick you described for earlier version issues, I was unable to delete the MonterailFullDark@conema.me.xpi file with Thunderbird running in the background because I got the error message that it was being used and couldn't be deleted.

Hopefully you will be able to update the theme for the new version because it is great!

Thanks!

**Comment by conema** [comment]
Hi @NJCurmudgeon, thanks for the information.
@cookieguru has already warned me about this on issue #23, I'll close this because it's a duplicated.

For the moment, I'm pretty busy and I haven't an ETA for that, I'll make the edits for made the theme compatible with beta versions as soon as possible.

**Comment by conema** [comment]
Just for update you, I posted an answer on issue #23, for the moment, that can't be fixed...
