### ISSUE TITLE
Message Tags not Visible in TB68

### ISSUE THREAD

**Issue by apaarfus** [conema/monterail-fulldark#32]
**Describe the bug**
Message tags not visible when theme is active in Thunderbird 68.  Disabling the extension makes them visible again.

**Screenshots**
Theme Enabled (blurred for privacy reasons):

![theme_error1](https://user-images.githubusercontent.com/38731016/70383647-4df8b380-193f-11ea-9d59-7028bcb4076d.png)

Theme Disabled (blurred for privacy reasons):

![theme_error2](https://user-images.githubusercontent.com/38731016/70383652-581ab200-193f-11ea-9861-664474343af1.png)

**Build information (please complete the following information):**
 - OS: Windows 7 Professional x64
 - Thunderbird Version: 68.3.0 x86
 - Theme Version: 2.0

**Additional context**
I'll be moving to Windows 10 Pro in a week's time; so I can report back if I notice any changes then.

**Comment by conema** [comment]
Hi @apaarfus, did you downloaded the theme directly from the repository (https://github.com/conema/monterail-fulldark/archive/master.zip)? This issue is the same as #30 and it should be resolved in one of the last commits.

PS: the version in the release page and the version in the thunderbird addons page is not yet update with the latest fixes.

**Comment by apaarfus** [comment]
I pulled the v2.0 release, rather than straight from Master.

I've just reinstalled with the master branch, which is indeed showing the appropriate colors for tags.
