### ISSUE TITLE
Email Background is white

### ISSUE THREAD

**Issue by Scoty43** [conema/monterail-fulldark#54]
How can i change the background from white to grey? It should have the same grey color as next to it.

![Zwischenablage-Bild (28 Oktober 2020)](https://user-images.githubusercontent.com/25227541/97414256-0fc40400-1904-11eb-99a7-8cd25d3934ca.png)

**Comment by conema** [comment]
Hi @Scoty43, the theme cannot directly change the email background, since it would break e-mails with a customized bg color. However, you can change the bg color with a TB settings. Go to Options -> General -> Language & Aspect -> Colors (button) -> change the color of the background. Remeber that this setting will work only on the e-mail withaout a background.

**Comment by Scoty43** [comment]
Ok thank you.
