### ISSUE TITLE
Lack of horizontal lines in the calendar

### ISSUE THREAD

**Issue by HomeArmy** [conema/monterail-fulldark#57]
**Describe the bug**
Lack of horizontal lines (half-hourly) in the weekly and daily calendar

**To Reproduce (if applicable)**
1. Go to Calendar tab click on Day or Week on the right upper side
2. See the horizontal lines?
3. No?
4. This is the bug. ;-)

**Expected behavior**
To see the horizontal hourly and half-hourly horizontal lines on the screen

**Build information (please complete the following information):**
 - OS: W10
 - Thunderbird 78.4.3

**Comment by conema** [comment]
Hi @HomeArmy, thank you for your issue. It should be fixed with the last commit, could you test it?
file: [monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5569021/monterail-fulldark.zip)

![immagine](https://user-images.githubusercontent.com/12801153/99709960-41ae2d80-2aa0-11eb-9136-38d5310a868c.png)
![immagine](https://user-images.githubusercontent.com/12801153/99710040-5be80b80-2aa0-11eb-8de4-5ef62242e85b.png)
