### ISSUE TITLE
The Top menu bar's background is light grey instead of dark... 

### ISSUE THREAD

**Issue by WebProd33** [conema/monterail-fulldark#71]
**Describe the bug**
The Top menu bar's background is light grey instead of dark

**Expected behavior**
Should be dark

**Screenshots**
![thunderbird_2021 07 29-1038-1890 120](https://user-images.githubusercontent.com/70518861/127469462-9e9e2e89-8923-47d9-90cb-7b8ba811e940.jpg)

**Build information (please complete the following information):**
 - OS: Windows 10 x64 20H2
 - Thunderbird 78.12.0 32-Bit

Any help to know what's going on please?

**Comment by conema** [comment]
Hi @WebProd33,
As you can see from the screenshots, this is the expected behaviour. If you want, you can change the light grey color (and all the other colors) by editing the root.css file here:
https://github.com/conema/monterail-fulldark/blob/d1c8e3f3e2a6d7bcb477327623311f05cc2b0ad2/content/skin/root.css#L28-L67


PS: I transfered your issue on the fulldark repository

**Comment by WebProd33** [comment]
THanks a lot for the help
